apiVersion: v1
kind: Deployment
metadata:
  name: capstone-udacity
spec:
  selector:
    matchLabels:
      app: capstone-udacity
  replicas: 1
  template:
    metadata:
      labels:
        app: capstone-udacity
    spec:
      containers:
        - name: capstone-udacity
          image: 120106008631.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone:latestgitr
          ports:
          - containerPort: 80