apiVersion: v1
kind: Service
metadata:
  name: capstone-udacity
  labels:
    app:  capstone-udacity
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: capstone-udacity